[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_counter = "86NMyAGyfKiwfmCofciSnFttXee3G3sd5oAoD8NsKNiC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/andrevants/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
